# Generated by Django 5.1.2 on 2024-10-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('pcat', models.CharField(blank=True, max_length=100, null=True)),
                ('pquan', models.IntegerField(blank=True, max_length=100, null=True)),
                ('pprice', models.IntegerField(blank=True, max_length=100, null=True)),
                ('pimage1', models.ImageField(blank=True, null=True, upload_to='p_images')),
                ('pimage2', models.ImageField(blank=True, null=True, upload_to='p_images')),
                ('pimage3', models.ImageField(blank=True, null=True, upload_to='p_images')),
                ('cman', models.CharField(blank=True, max_length=100, null=True)),
                ('coun', models.CharField(blank=True, max_length=100, null=True)),
                ('cdesc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
