# Generated by Django 5.1.2 on 2024-10-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cdesc',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cman',
            new_name='pman',
        ),
    ]
