# Generated by Django 5.1.2 on 2024-10-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0003_rename_cdesc_product_pdesc_rename_cman_product_pman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pquan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
