# Generated by Django 5.1.2 on 2024-10-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Password1', models.CharField(blank=True, max_length=100, null=True)),
                ('Password2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
