# Generated by Django 5.1.2 on 2024-10-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_signup_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup_db',
            old_name='Username',
            new_name='Username1',
        ),
    ]
