# Generated by Django 5.1.2 on 2024-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_username_signup_db_username1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_db',
            name='Contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
