# Generated by Django 5.1.2 on 2024-11-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_signup_db_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('Product', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Tprice', models.IntegerField(blank=True, null=True)),
                ('Uname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
