# Generated by Django 5.1.2 on 2024-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
