# Generated by Django 5.1.2 on 2024-11-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_orderdb_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Pro_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_images'),
        ),
    ]
